# Generated by Django 5.2.7 on 2026-06-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joya',
            name='categoria',
            field=models.CharField(choices=[('Anillos', 'Anillos'), ('Pulseras', 'Pulseras'), ('Collares', 'Collares'), ('Otra', 'Otra')], default='Otra', max_length=50),
        ),
    ]
