# Generated by Django 5.2.7 on 2026-06-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_joya_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='joya',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='joyas/'),
        ),
        migrations.AddField(
            model_name='joya',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='joyas/'),
        ),
        migrations.AddField(
            model_name='joya',
            name='imagen_4',
            field=models.ImageField(blank=True, null=True, upload_to='joyas/'),
        ),
    ]
